Thu Sep  1 16:28:36 CEST 2022

diff --git a/gmarks2 b/gmarks2
--- a/gmarks2
+++ b/gmarks2
@@ -21,6 +21,11 @@
 #1	22	8. Conditional Expectation
 #1	24	9. Appendix: Lebesgue measure. Caratheodory extension
 
+
+pages() { pdfinfo "$1" | grep Pages | sed 's/^[^:]*:\s*//'; }
+
+# count=0; for i in {1..7}; do gmarks2 i2o -a $count $i.info; count="$(( count + $(pages "$i.pdf") ))"; done
+
 DEL='[\t]+'
 OFFSET=0
 
@@ -97,43 +102,39 @@ o2i() {
 }
 
 i2o() {
-    OPTIND=0;
-    while getopts ":h" o; do
-        case "${o}" in
-            h) i2o_usage; exit 0;;
-        esac
-    done
-    shift $((OPTIND-1))
-    
-    [ "$#" -lt 1 ] && {
-        echo "ERROR: Not enough arguments!"; i2o_usage; exit 1;
+  OPTIND=0;
+  while getopts ":a:h" o; do
+    case "${o}" in
+      h) i2o_usage; exit 0;;
+      a) OFFSET=${OPTARG} ;;
+    esac
+  done
+  shift $((OPTIND-1))
+  
+  [ "$#" -lt 1 ] && {
+    echo "ERROR: Not enough arguments!"; i2o_usage; exit 1;
+  }
+
+  IFS=':'
+  grep Bookmark "$1" | {
+    # level=0; pnr=0; title=""
+    prt() {
+        [ -z "$level" ] || printf "$level\t$(( $pnr + $OFFSET ))\t$title\n"
     }
-        
-	IFS=':'
-	grep Bookmark "$1" | while read line; do
-		# Shuld probably write some c code
 
-		# This does not work when the title contains :
-		#read -ra ADDR <<< "$line"
-		#case ${ADDR[0]} in
-		#		BookmarkBegin) echo "$level$pnr$title" ;;
-		#		BookmarkLevel) level="${ADDR[1]}" ;;
-		#		BookmarkTitle) title="${ADDR[1]}" ;;
-		#		BookmarkPageNumber) pnr="${ADDR[1]}" ;;
-		#		*) 
-		#esac
+    while read line; do
+      key="$(echo "$line" | cut -d':' -f1)"
+      value="$(echo "$line" | sed "s/^[^:]*: *//" )"
 
-		# This is a realy slow solution
-		key=$(echo $line | cut -d':' -f1) 
-		value=$( echo $line | sed "s/^.*: //" )
-		case $key in
-				BookmarkBegin) echo "$level$pnr$title" ;;
-				BookmarkLevel) level="$value" ;;
-				BookmarkTitle) title="$value" ;;
-				BookmarkPageNumber) pnr="$value" ;;
-				*) 
-		esac
-	done 
+      case $key in
+      	BookmarkBegin)       prt             ;;
+      	BookmarkLevel)       level="$value"  ;;
+      	BookmarkTitle)       title="$value"  ;;
+      	BookmarkPageNumber)  pnr="$value"    ;;
+      esac
+    done 
+    prt
+  }
 }
 
 addi(){
@@ -200,6 +201,7 @@ join() {
 	for file in "$@"; do 
 		pdftk $file dump_data_utf8 > /tmp/$file.info;
 	done
+    # TODO: Use jq
 	python -c '
 import sys; from pdf_dump import *
 off=0; 
@@ -207,7 +209,7 @@ for fn in sys.argv[1:]:
     root=read_info("/tmp/%s.info" % fn); info2otl(root,pgn_off=off)
     off+=root["NumberOfPages"]
 	' "$@" > /tmp/pdfjoin.otl
-	otl2info /tmp/pdfjoin.otl > pdfjoin.info
+	o2i /tmp/pdfjoin.otl > pdfjoin.info
 	echo "Combining pdfs"
 	pdfjoin --outfile /tmp/pdfjoin.pdf -- "$@"
 	echo "Adding metadata"
diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -1,73 +1,155 @@
 #!/bin/bash
 
+source .uservars
 [ -z $NOTEBOOK_DIR ] && NOTEBOOK_DIR="~/NOTEBOOK"
 
+PRINT=false
+NEWWIN=false
+DELETE=false
+RENAME=false
+
+_dmenu() {
+    dmenu -i -l 20 
+}
+
+_menu() {
+  cat "$1" | _dmenu > "$2"
+  # _tmenu $1 $2
+}
 
 list(){
     ls "$NOTEBOOK_DIR" | grep 'md$' | sed 's/.md$//'
 }
 
-dmenu_browse() {
-    echo "$(list | dmenu)" # || return
-    # urxvt -e nvim "$name.md"
-}
-
 open() {
-    echo $1
-
-    $NEWWIN && { urxvt -e nvim -p "$@"; } \
+    $NEWWIN && { ONSTART="nvim -p \"$@\"" $TERMINAL; } \
         || nvim -p "$@";
 }
 
+
+choose() {
+  [ -z "$1" ] || { echo "$1"; return; }
+  _menu <( list ) $2
+}
+
+delete() {
+  [ -z "$1" ] && return
+  prompt "Do you realy want delete '$1'?" && \
+      rm "$1.md"
+}
+
+rename() {
+  [ -z "$1" ] && return
+  namef=$(mktemp)
+  printf "%s" "$1" > $namef
+
+  $NEWWIN && { ONSTART="nvim \"$namef\"" $TERMINAL; } \
+      || nvim "$namef";
+
+  newname="$(< $namef sed q1)"
+  rm $namef 
+
+  ## TODO: Check that the name is not problematic
+  case $newname in
+    $1) return ;;
+
+    _*) printf "ERROR: The filename may not start with underscore\n" \
+            > /dev/stderr;
+        exit 1;;
+    */*) printf "ERROR: The filename may not contain '/' \n" \
+            > /dev/stderr;
+        exit 1;;
+    "") printf "ERROR: The filename may not be empty \n" \
+            > /dev/stderr;
+        exit 1;;
+  esac
+
+  # if ! [[ $newname =~ ^[a-zA-Z]+$ ]]; then
+  #   printf "ERROR: Invalid filename '$newname' \n" \
+  #           > /dev/stderr;
+  #   exit 1;
+  # fi
+
+  mv "$1.md" "$newname.md";
+}
+
 main() {
-    [ -d $NOTEBOOK_DIR ] || mkdir $NOTEBOOK_DIR
-    cd "$NOTEBOOK_DIR";
+  [ -d "$NOTEBOOK_DIR" ] || mkdir $NOTEBOOK_DIR
+  cd "$NOTEBOOK_DIR";
+ 
+  choisef=$(mktemp)
 
-    $BROWSE && {
-        note="$(dmenu_browse).md"
-        NEWWIN=true
-    } || {
-        note="$1.md"
-    }
+  $RENAME && { 
+      choose "$1" $choisef || exit 0;
+      rename "$(cat $choisef)"; 
+      rm $choisef 
+      exit 0;
+  }
+  $DELETE && { 
+      choose "$1" $choisef || exit 0;
+      delete "$(cat $choisef)"; 
+      rm $choisef 
+      exit 0;
 
-    $PRINT && {
-        [ -f $note ] && cat "$note"
-        return
-    }
+      note=$(choose "$1") || exit 0;
+      delete "$note"; 
+      exit 0; 
+  }
+  $PRINT && { 
+      choose "$1" $choisef || exit 0;
+      delete "$(cat $choisef)"; 
 
-    [ -f "$note" ] && open "$note" \
-        || open .
+      note="$(cat $choisef)"
+      [ -f "$note" ] && cat "$note"; exit 0; 
+      rm $choisef 
+      exit 0; 
+  }
+
+  [ -z "$1" ] || { 
+      open "$1.md"; 
+      exit 0; 
+  }
+
+  cases="_New,_Remove,_Rename"
+  _menu <( list; echo "$cases" | tr , '\n'; ) $choisef
+  choise="$( { list; echo "$cases" | tr , '\n'; } | _dmenu)" \
+      || exit 0
+
+  case "$choise" in
+      "_New") 
+        fn="$(_dmenu)" || exit 0;
+        open "$fn.md" ;;
+      "_Remove") delete "$(choose)" ;;
+      "_Rename") rename "$(choose)";;
+      *)         echo Hey; open "$choise.md" ;;
+  esac;
 }
 
 _usage() { 
-    echo "nb - notebook managment script"
+    echo "$ nb [OPTIONS] [note]"
+    echo ""
+    echo "Notebook managment script"
     echo ""
     # echo " Description "
     # echo ""
     echo "options:"
-    echo "  -b, --browse    browse the notebook files with dmenu"
-    echo "  -p, --print     print the content of notebook"
-    echo "  -nw, --newwin   open in new window"
-    echo "  -h, --help      print this message"
+    echo "  -p,  --print     print the content of notebook"
+    echo "  -nw, --newwin    open in new window"
+    echo "  -d,  --delete    delete note"
+    echo "  -rn, --rename    rename note"
+    echo "  -h,  --help      print this message"
 }
-
-_invopt() {
-    echo "Incorrect options provided '$1'"; usage; exit 1
-}
-
-BROWSE=false
-PRINT=false
-NEWWIN=false
 
 # Read arguments
 POSITIONAL=()
 while [[ $# -gt 0 ]]; do
 case $1 in
-    --browse) BROWSE=true ;;
-    --print|-p) PRINT=true ;;
-    --newwin|-nw) NEWWIN=true ;;
-    -h|-?|--help) _usage; exit 0 ;;
-    -*) _invopt ;;
+    --print|-p)     PRINT=true ;;
+    --delete|-d)    DELETE=true ;;
+    --rename|-rn)   RENAME=true ;;
+    --newwin|-nw)   NEWWIN=true ;;
+    -h|-?|--help)   _usage; exit 0 ;;
+    -*) echo "Incorrect options provided '$1'"; exit 1 ;;
     *) POSITIONAL+=("$1") ;;
 esac; shift;
 done
diff --git a/prompt b/prompt
--- a/prompt
+++ b/prompt
@@ -1,18 +1,40 @@
 #!/bin/sh
-# A dmenu binary prompt script.
-# Gives a dmenu prompt labeled with $1 to perform command $2.
 # For example:
-#           Depricated
-# `./prompt "Do you want to shutdown?" "shutdown -h now"`
-# OR better: 
 # `./prompt "Do you want to shutdown?" \
 #       && shutdown -h now || echo "Dose not turn off"`
 
-# Custimisable and default sould read from a lang file
 YES="Yes"; NO="No" 
 
-_dmenu() { dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray; }
+_dmenu() { 
+    dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray; 
+}
 
-[ "$(printf "$NO\\n$YES" | _dmenu "$1" )" = "$YES" ] || exit 1 
-[ -z "$2" ] || (echo "$2" | bash)  # Depricated 
+main() {
+  [ "$(printf "$NO\\n$YES" | _dmenu "$1" )" = "$YES" ] || exit 1 
+}
 
+_usage() { 
+  echo "$ prompt [options] <Prompt>"
+  echo ""
+  echo "Yes/No prompt using dmenu."
+  echo "Exits with value 0 if Yes and 1 if No."
+  echo ""
+  echo "options:"
+  echo "  -h, --help      print this message"
+  echo ""
+  echo "Example:"
+  echo "  $ ./prompt \"Do you want to shutdown?\" \\"
+  echo "         && shutdown -h now || echo \"Dose not turn off\""
+} 
+
+
+# Read arguments
+POSITIONAL=()
+while [[ $# -gt 0 ]]; do
+case $1 in
+  -h|-?|--help) _usage; exit 0 ;;
+  -*) echo "Invalid option '$1'" > /dev/stderr; exit 1 ;;
+  *) POSITIONAL+=("$1") ;;
+esac; shift;
+done
+main "${POSITIONAL[@]}"
